spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      group-id: listenerTrasacaoId
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: "false"
    topic:
      transactions: ${KAFKA_TOPIC:transacoes}
  datasource:
    username: root
    url: ${BANCO_DADOS:jdbc:mysql://localhost:3306/transacoes}
    testWhileIdle: 'true'
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port : 8081
