spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
      group-id: listenerTrasacaoId
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: "false"
    topic:
      transactions: ${KAFKA_TOPIC:transacoes}
  datasource:
    username: ${DBUSERNAME:root}
    password: ${DBPASSWD:password}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/transacoes}
    testWhileIdle: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/transacaorealm}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/transacaorealm/protocol/openid-connect/certs}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
server:
  port : ${PORT:8081}
